apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d1qf6z70w-dotnet-basic
  janus-idp.io/tekton: d1qf6z70w-dotnet-basic
  backstage.io/kubernetes-id: d1qf6z70w-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: d1qf6z70w-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
